write custom clone step

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -42,19 +42,21 @@ jobs:
           sudo chmod -R 777 "$RUNNER_TEMP"
           ls -alh ..
 
-      # Check out repo
       - name: Check out repo
-        uses: actions/checkout@v4.2.2
-        with:
-          # https://github.com/actions/checkout/issues/1575#issuecomment-2283621510
-          clean: false
-          #submodules: true
-          # https://stackoverflow.com/questions/72978485/git-submodule-update-failed-with-fatal-detected-dubious-ownership-in-repositor
-          set-safe-directory: false
+        shell: bash -exuo pipefail {0}
+        run: |
+          git clone "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" -b "${GITHUB_HEAD_REF}" "${RUNNER_WORKSPACE}"
+      ## Check out repo
+      #- name: Check out repo
+      #  uses: actions/checkout@v4.2.2
+      #  with:
+      #    #submodules: true
+      #    # https://stackoverflow.com/questions/72978485/git-submodule-update-failed-with-fatal-detected-dubious-ownership-in-repositor
+      #    set-safe-directory: true
 
       # TODO use //tool/ci.ml
       - name: Run CI
-        shell: bash -exo pipefail {0}
+        shell: bash -exuo pipefail {0}
         run: |
           eval $(opam env --switch=default-switch)
           make get
